### ISSUE TITLE
Does liveEndpoint definitely not need to be set?

### ISSUE THREAD

**Issue by coatesap** [pedanticantic/omnipay-evo#3]
Does the endpoint declared [here](https://github.com/pedanticantic/omnipay-evo/blob/13b6bff90040525bb51940ce338ab99e4cfbd450/src/Omnipay/Evo/Message/PurchaseRequest.php#L16), definitely not need to be set?

**Comment by pedanticantic** [comment]
Thanks for the question. I've investigated and the endpoints are not used at all. The flow is that the tokenUrl is used, then the user is redirected to the redirectUrl, and then returned to the client site.

I have now removed all references to endpoints in the purchase class.
