### ISSUE TITLE
Incorrect Namespace

### ISSUE THREAD

**Issue by greydnls** [pedanticantic/omnipay-evo#5]
Hi, I very much value your work on this gateway, however it shouldn't e using the Omnipay namespace. Can you please update it to use your own namespace?

**Comment by pedanticantic** [comment]
Hi Kayla, sorry I had no idea I shouldn't be using the Omnipay namespace. I'll change both repos as soon as I can.
Regards,
Glenn

**Comment by pedanticantic** [comment]
Namespace is now updated and the driver has been tested.

Regards,
Glenn
